### ISSUE TITLE
BrotliStream quality levels from 5 to 9 don't work on NetCore. 

### ISSUE THREAD

**Issue by Alfalover** [master131/BrotliSharpLib#1]
That exception is throwed on Quality levels 5,6,7,8 and 9

System.NullReferenceException: Object reference not set to an instance of an object.

StackTrace:	
at BrotliSharpLib.Brotli.ShouldUseComplexStaticContextMap(Byte* input, SizeT start_pos, SizeT length, SizeT mask, Int32 quality, SizeT size_hint, ContextType* literal_context_mode, SizeT* num_literal_contexts, UInt32** literal_context_map)
   at BrotliSharpLib.Brotli.DecideOverLiteralContextModeling(Byte* input, SizeT start_pos, SizeT length, SizeT mask, Int32 quality, SizeT size_hint, ContextType* literal_context_mode, SizeT* num_literal_contexts, UInt32** literal_context_map)
   at BrotliSharpLib.Brotli.WriteMetaBlockInternal(MemoryManager& m, Byte* data, SizeT mask, UInt64 last_flush_pos, SizeT bytes, Boolean is_last, BrotliEncoderParams* params_, Byte prev_byte, Byte prev_byte2, SizeT num_literals, SizeT num_commands, Command* commands, Int32* saved_dist_cache, Int32* dist_cache, SizeT* storage_ix, Byte* storage)
   at BrotliSharpLib.Brotli.EncodeData(BrotliEncoderStateStruct& s, Boolean is_last, Boolean force_flush, SizeT* out_size, Byte** output)
   at BrotliSharpLib.Brotli.BrotliEncoderCompressStream(BrotliEncoderStateStruct& s, BrotliEncoderOperation op, SizeT* available_in, Byte** next_in, SizeT* available_out, Byte** next_out, SizeT* total_out)
   at BrotliSharpLib.BrotliStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count, BrotliEncoderOperation operation)
   at BrotliSharpLib.BrotliStream.FlushCompress(Boolean finish)
   at BrotliSharpLib.BrotliStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()

**Comment by master131** [comment]
I am unable to reproduce this issue in a .NET Core 1.0 & 1.1 project in VS2017 on Windows 10. What environment are you running this on? Can you provide me with some minimal code and a test file which can reproduce this issue?

**Comment by Alfalover** [comment]
I'm unable to reproduce this on my Windows 10 home computer, its an issue I
found at job computer (I don't have remote access), I'm currently on
holidays until next monday.

I could not remember if issues happends on Windows 10 or on Ubuntu 17.04 ,
On Monday I will try to reproduce again and send you more details.

Thank you

**Comment by HammNCheez** [comment]
We just switched our app over to use this Brotli library and 99% of the time it was working perfectly but every so often it would throw an error with the same stack trace as the original comment from @Alfalover. We were using a quality level of 5 and when we bumped it down to 4 it stopped throwing the error.

I don't know if it was just because of the size of the array, The error happens consistently when we are passing in a byte array of length 1115717.

We are using the latest 0.2.1 from Nuget and .Net core 2.0.0

**Comment by master131** [comment]
I'll have a look into this when I have time. Due to the sheer complexity of the code it might take some time to debug.

**Comment by Rattenhirn** [comment]
Hello, I ran into this issue as well and did some debugging. This happens in "ShouldUseComplexStaticContextMap", which is only called when compression quality >= MIN_QUALITY_FOR_CONTEXT_MODELING (5) and a size_hint of 2^20 or larger, which is most of the time equivalent to the size of the input data.
So, if you compress a block bigger than 1 MiB with quality 5 or higher, it'll fail.

Luckily, the actual bug is just a copy paste error and can be easily fixed. I have attached a file with a fix, not sure if this is the most C# way to do it, but it is functional.

It would be great if you could update the Nuget package!

[Encode.zip](https://github.com/master131/BrotliSharpLib/files/2657260/Encode.zip)

**Comment by master131** [comment]
Thanks @Rattenhirn, I've added the fix to the latest build.
